# Generated by Django 5.1.3 on 2024-11-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Varient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='Varient',
        ),
    ]
