# Generated by Django 5.1.3 on 2024-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varient', '0002_rename_variant_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='price_with_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (with shipping cost)'),
        ),
    ]
