# Generated by Django 5.1.3 on 2024-11-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varient', '0003_alter_sizevariant_price_with_shipping'),
        ('product_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_apis.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='varient',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_apis.product'),
            preserve_default=False,
        ),
    ]
