# Generated by Django 5.1.3 on 2024-11-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mst_product_status',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_material',
                'indexes': [models.Index(fields=['is_active'], name='mst_materia_is_acti_840aa6_idx'), models.Index(fields=['material_title'], name='mst_materia_materia_58db07_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=250)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('subcategories', models.JSONField(blank=True, default=list)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='product_apis.productcategory')),
            ],
            options={
                'db_table': 'mst_product_category',
                'ordering': ['category_id'],
                'unique_together': {('category_title', 'parent_id')},
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('occasion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occasion_title', models.CharField(max_length=250)),
                ('short_description', models.CharField(blank=True, max_length=250, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_occasions', to='product_apis.occasion')),
            ],
            options={
                'db_table': 'mst_occasion',
                'indexes': [models.Index(fields=['parent_id'], name='mst_occasio_parent__0fc8e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=8, null=True)),
                ('user_id', models.CharField(max_length=8, null=True)),
                ('product_title', models.CharField(max_length=500)),
                ('is_customisable', models.BooleanField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_perc', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('discount_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material_name', models.CharField(blank=True, max_length=250, null=True)),
                ('color_variants', models.CharField(blank=True, max_length=500, null=True)),
                ('surface', models.CharField(blank=True, max_length=100, null=True)),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
                ('has_size_variant', models.BooleanField(default=False)),
                ('has_color_variant', models.BooleanField(default=False)),
                ('variant_title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_personalised', models.BooleanField(default=False)),
                ('personalisation_note', models.CharField(blank=True, max_length=500, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('public_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_viewed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('isapproved', models.BooleanField(default=False)),
                ('isdisapproved', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=8, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_apis.material')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_apis.productcategory')),
                ('relevent_Category_id', models.ManyToManyField(to='product_apis.productcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_apis.productstatus')),
            ],
            options={
                'db_table': 'mst_products',
                'indexes': [models.Index(fields=['status'], name='mst_product_status__3f55e1_idx'), models.Index(fields=['category'], name='mst_product_categor_d69500_idx'), models.Index(fields=['material'], name='mst_product_materia_d76ba5_idx')],
            },
        ),
    ]
